version: "2"

services: 
  asciidoctor:
    image: asciidoctor/docker-asciidoctor:1
    volumes: 
      - .:/documents
    working_dir: /documents
    entrypoint: asciidoctor -D . --failure-level WARN -r asciidoctor-bibtex -r asciidoctor-diagram -a mathjax --trace --backend=html5 index.adoc -o open-simulation-interface_localbuild.html