= OSI Documentation

This repo contains most of the AsciiDoc-based part of the documentation.
It contains generals parts of the content and a CI-pipeline that renders the document with Antora.

NOTE: The actual hosting has been moved to the generator repository (see link below).

== ASAM OSI (R) official documentation

See the documentation https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/index.html[here].


== Antora build pipeline
image::https://github.com/OpenSimulationInterface/osi-antora-generator/actions/workflows/site-build.yml/badge.svg?branch=main[link=https://github.com/OpenSimulationInterface/osi-antora-generator/actions/workflows/site-build.yml]

NOTE: This pipeline runs on https://github.com/OpenSimulationInterface/osi-antora-generator.

== How To build and change documentation locally

IMPORTANT: These instructions relate ONLY to the Asciidoctor build.
For Antora, check the https://github.com/OpenSimulationInterface/osi-antora-generator[ASAM OSI Antora generator].


The following instructions show how to build the document locally.
Take note that the document is built with a version 'localbuild' in the document and filename.

The instruction should work on Windows, Linux, and MacOS.

. *Precondition*: have docker and docker-compose installed.
+
TIP: Official installation can be found https://docs.docker.com/get-docker/[here].

. Clone this repository with submodules.
+
[source, shell]
----
git clone https://github.com/OpenSimulationInterface/osi-documentation.git
git submodule update --init
----

. Clone OSI and OSMP with submodules *into* the osi-documentation folder
+
[source, shell]
----
cd osi-documentation
git clone https://github.com/OpenSimulationInterface/open-simulation-interface.git
git clone https://github.com/OpenSimulationInterface/osi-sensor-model-packaging.git
----

. Check file ``docker-compose.yml`` with the following content:
+
[source, yaml]
----
  version: "2"

  services:
  asciidoctor:
      image: asciidoctor/docker-asciidoctor:1
      volumes:
      - .:/documents
      working_dir: /documents
      entrypoint: asciidoctor -D . --failure-level WARN -r asciidoctor-bibtex -r asciidoctor-diagram -a mathjax --trace --backend=html5 index.adoc -o open-simulation-interface_localbuild.html
----

. Run
+
[source, shell]
----
docker-compose run asciidoctor
----

. *Result*: Document is build as `open-simulation-interface_localbuild.html` in the folder osi-documentation.
