= Foreword

The {THIS_STANDARD} (Open Simulation Interface) is a specification for interfaces between models and components of a distributed simulation.
OSI is strongly focused on the environmental perception of automated driving functions.

The complexity of automated driving functions is rapidly increasing, which means the requirements for testing and development methods are growing too.
Testing in virtual environments makes it possible to control and reproduce environment conditions.

To enable the widespread use of driving simulators for developers of functions, generic and standardized interfaces are needed for the  connection between the function-development framework and the simulation environment.
OSI permits easy and straight-forward compatibility between automated driving functions and the variety of driving-simulation frameworks that are available.
OSI addresses the emerging standard ISO 23150 cite:[iso23150] for a real sensors’ standardized communication interface.
OSI defines generic interfaces to ensure the modularity, integrability, and interchangeability of the individual components.

The vision is to make it possible to connect any automated driving function to any driving simulator and emerging new hardware sensor generations using a standardized ISO 23150 cite:[iso23150] interface.
This will simplify integration, significantly strengthening the accessibility and usefulness of virtual testing in the process.

