[glossary]
= Terms and definitions

Co-Simulation (CS)::
Co-Simulation (CS) is a type of Functional Mockup Unit (FMU). +
Co-Simulation FMUs contain their own numerical solver.
The importing tool sets the FMU inputs, asks the FMU to step forward a given time, and reads the FMU output after the step is completed. +
+
(Source: https://www.modelon.com/functional-mock-up-interface-fmi/)

Ego vehicle::
An externally controlled vehicle used for scenario descriptions. +
For evaluation of automated driving systems, the Ego vehicle will be the one controlled by the system-under-test.
For human driver experiments, the Ego vehicle will be the one driven by the human driver. +
+
(Source: Open SCENARIO User Guide 1.0)

Environmental effect model::


FMI::
Functional Mockup Interface; +
The Functional Mock-up Interface (FMI) is a free standard that defines a container and an interface to exchange dynamic models using a combination of XML files, binaries and C code zipped into a single file. +
+
(Source: https://fmi-standard.org/)

FMU::
Functional Mockup Unit; +
FMU is a file with the extension _.fmu_ It contains a simulation model that adheres to the FMI standard.
There are two different kinds of FMUs: Model Exchange (ME) and Co-Simulation (CS) +
+
(Source: https://www.modelon.com/functional-mock-up-interface-fmi/)

Ground truth::
The ground truth describes the simulated environment containing all simulated objects in the global coordinate system at consecutive time instances. It is based on data available to the simulation environment. +
+
(Source: OSI User Guide)

Model Exchange (ME)::
Model exchange (ME) is a type of Functional Mockup Unit (FMU).

Object coordinate system::


OSI::
Open Simulation Interface; +
The Open Simulation Interface (OSI) is a specification for interfaces between models and components of a distributed simulation. OSI has a strong focus on environmental perception of automated driving functions. It also specifies interfaces for modeling traffic participants. +
+
(Source: OSI User Guide)

OSMP::
OSI Sensor Model Packaging; +
OSI Sensor Model Packaging (OSMP) specifies how models that use Open Simulation Interface (OSI) in simulation environments are packaged in accordance with the Functional Mock-up Interface 2.0 (FMI 2.0). +
+
(Source: OSMP specification)

Sensor coordinate system::

Sensor model::

Sensor view::
The sensor view is derived from GroundTruth and used as input to sensor models.

The sensor view information is supposed to provide input to sensor models for simulation of actual real sensors.

(Source: OSI User Guide)

Traffic participant::

Traffic participant model::

World coordinate system::
Coordinate system for all entities that are part of ground truth.
The world coordinate system is an inertial x/y/z-coordinate system. The origin is the global reference point that is determined by the environment simulation. This reference point may be derived from map data or other considerations.