[#top-guidelines_for_contributions]
= Guidelines for contributions

ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]

Commit guidelines exist to ensure the transparency and intelligibility of the commit history.
{THIS_STANDARD} enforces the following commit guidelines:

- Prefer small atomic commits over large ones that do many things.
- Do not mix refactoring and new features.
- Do not mix style changes, for example indentation changes, with actual code changes.
- If you add new messages to a *.proto file, add appropriate documentation as well.
- Run the unit tests for comment compliance to check if you followed the correct syntax guidelines for *.proto files.
- Follow the guidelines for commit messages.
- Sign off commit messages.
- Name branches meaningfully and consistently.
- If a commit contains work-in-progress, add the _WIP_ label to the commit message.

**Related topics**

- <<top-guidelines_for_writing_commit_messages>>
- <<top-interface_conventions>>
- <<top-commenting_on_messages>>
- <<top-commenting_on_fields_and_enums>>
- <<top-signing_off_commits>>