[#top-guidelines_for_creating_literary_references]
= Guidelines for creating literary references

ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]

When citing literature in the reference documentation, adhere to the following guidelines:

* All sources shall be primary sources. Sources like Wikipedia are not allowed.
* OSI uses _APA style_ references from the American Psychological Association.
* In the text, sources are cited using numbers in brackets.
* In the references list, the number in brackets is resolved to a full citation.
* Titles shall be written in italic, using `<em>title</em>`.
* If the list contains more than one entry, add `\n` at the end of the line to create a line break within the list.
* Author names shall be written as <surname>, <initial(s)>.
* Editor names shall be written as <initial(s)> <surname>.
* Page numbers are optional and may be used with long texts or for referencing specific sections.

**Templates**

Use the following templates for creating properly styled references:

Compilation::
----
<author1>, <author2>, <author3> & <author4>. (<year>). Contribution in a compilation title. <em><Compilation Title></em>. <edition>. <page(s)>. <publisher>. <location>. <doi>. <page(s)>.
----
Book::
----
<author1>, <author2> & <author3>. (<year>). <em><book (monograph) title></em>. <edition>. <publisher>. <doi>. <page(s)>.
----
Chapter in a book::
----
<author1> & <author2>. (<year>). <book chapter title>. In <editor1> & <editor2> (Eds.), <em><book title></em> (<page(s)>). <publisher>. <doi>. <page(s)>.
----
Article in a journal::
----
<author1> & <author2>. (<year>). <journal article title>. <em><journal title></em>. <page(s)>. <location>. <doi>. <page(s)>.
----
Phd thesis::
----
<author>. (<year>). <em><Phd thesis title></em>. Phd. thesis. <location>. <university>. <doi or url>. <page(s)>.
----
Online article::
----
<author>. (<year>, <month> <day>). <em><internet article title></em>. Retrieved <month> <day>, <year>, from <url>.
----
Standard::
----
<standarding organisation>. (<year>). <em><title of the standard></em>. (<standard identifier>). <location>.
----
Patent::
----
<author>. (<year>). <em><patent title and id></em>. <location>. <organisation>.
----

More sample templates are available at https://apastyle.apa.org.


**Example**

[source,protobuf,linenums]
----
    // [...]
    // \par References:
    // [1] DIN Deutsches Institut fuer Normung e. V. (1982). <em>DIN 5031-3 Strahlungsphysik im optischen Bereich und Lichttechnik - Groessen, Formelzeichen und Einheiten der Lichttechnik</em>. (DIN 5031-3:1982-03). Berlin, Germany. \n
    // [2] Rapp, C. (2017). Grundlagen der Physik. In <em>Hydraulik fuer Ingenieure und Naturwissenschaftler</em> (pp.23-36). Springer Vieweg. Wiesbaden, Germany. https://doi.org/10.1007/978-3-658-18619-7_3. p. 105.
    //
    optional double atmospheric_pressure = 1;
}
----
