ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]
[#top-interface_conventions]
= Interface conventions

OSI messages, enums, field messages, and field enums shall comply with OSI interface conventions.
These conventions ensure that message definitions and the corresponding classes are consistently named and easy to read.

Message names shall use _PascalCase_.

[source,protobuf,linenums]
----
message EnvironmentalConditions
{
}
----

Message field names shall use _snake_case_.

[source,protobuf,linenums]
----
message EnvironmentalConditions
{
    optional double atmospheric_pressure = 1;
}
----

Enum names shall use _PascalCase_.

[source,protobuf,linenums]
----
message EnvironmentalConditions
{
    optional double atmospheric_pressure = 1;

    enum AmbientIllumination
    {
    }
}
----

Enum field value names shall use _UPPER_SNAKE_CASE_.
Enum field value names shall always be prefixed with the name of the corresponding enum.

For enum fields that are concerned with ground truth or sensor data, the first two enum values shall always be defined with the following rules:
The first enum field value shall always use the suffix _UNKNOWN_.
The second enum field value shall always use the suffix _OTHER_.

[source,protobuf,linenums]
----
message EnvironmentalConditions
{
    optional double atmospheric_pressure = 1;

    enum AmbientIllumination
    {
        AMBIENT_ILLUMINATION_UNKNOWN = 0;

        AMBIENT_ILLUMINATION_OTHER = 1;

        AMBIENT_ILLUMINATION_LEVEL1 = 2;
    }
}
----

Other enum fields, especially purely technical fields, can deviate from the rules for the first two field values.
